#!/bin/sh
for name in target/*.jar ; do
  CP=$CP:$name
done

if [ "$1" == "-debug" ] ; then
    DEBUG_OPTS="-J-Xdebug -J-Xnoagent -J-Djava.compiler=NONE -J-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
    shift
fi

scala $DEBUG_OPTS -cp $CP -Yrepl-sync $@ -i scripts/repl-load.scala
